### ISSUE TITLE
unclear issue around 'Linalg' for openblas (on windows amd64)

### ISSUE THREAD

**Issue by stonebig** [JuliaLang/pyjulia#34]
hi,

On Windows 32 bit mode, I get a fully functional Julia/Pyjulia/Juliamagic/IJulia
On Windows 64bit mode, I have two strange events, that may be related:
- Ijulia kernel die the first time (I have to restart it, then it's ok) with a
````
Timeout waiting for kernel_info reply
````

- pyjulia hangs , but the same voluntary treatment (restart kernel) makes it ok after
````
error initializing module LinAlg
ccall: could not find function openblas_get_config_64_ in library openblas
````

![pyjulia_and_lib_openblas](https://cloud.githubusercontent.com/assets/4312421/6188864/f5a6cadc-b395-11e4-9f7c-0a427fe2ea09.GIF)

side note: in my path, the openblas library given per Carl Kleffner (for python), is before the openblas potentially in julia dll list
==> there could be a mutual incompatibility issue there, but I don't guess how to solve it

https://bitbucket.org/carlkl/mingw-w64-for-python/downloads
`based on gcc-4.9.2 right now as well as an update of the openblas-0.2.12 builds`

**Comment by jiahao** [comment]
Do you know if the OpenBLAS you are using is compiled with ILP64=1 ? (See [this comment](https://github.com/Homebrew/homebrew-science/issues/48#issuecomment-11636954)) Julia requires this to be true by default.

**Comment by stonebig** [comment]
good question, I ask to Carl

**Comment by carlkl** [comment]
You can try to remove ```libopenblas.dll``` from ```tools/mingw32/bin``` (or move it to another place), as it is in the ```PATH``` within the winpython environment. ```libopenblas.dll``` is not needed in that context.

**Comment by stonebig** [comment]
Thank you for the quick answer, Carl.
trying the `fast` solution right now

**Comment by stonebig** [comment]
ok, so:
- on Ijulia, the kernel dies because of timeout  then restart immediatly and all is ok
- on python + pyjulia module, everything looks correct

==> so next issue, is a the timeout problem, but maybe rather a ipython one.
