### ISSUE TITLE
converting python lists to arrays

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/pyjulia#40]
It seems like all 1d lists in python are converted to ``Array{Any,1}``. Can we get tighter types?
I'm willing to hack this a bit, where does this transformation take place in the code?

**Comment by jakebolewski** [comment]
@mlubin it takes place in PyCall.jl

**Comment by mlubin** [comment]
Oh, CC @stevengj

**Comment by jakebolewski** [comment]
@mlubin you can't really infer a tighter bound as the elements may change at any time.  Think of a background thread updating elements of a python list with randomly typed data (such as promotion from ints -> bigints which python does transparently).  Achieving greater type stability could only be done when the list is copied at a certain point in time and only by reflecting the type of all objects as you iterate through the entire list (assuming you have an exclusive lock on the data structure).

**Comment by mlubin** [comment]
Fair enough, is the best workaround to use numpy arrays?

**Comment by jakebolewski** [comment]
@mlubin yes that would be better.  Support for arbitrary typed buffer objects in Python (including numpy arrays) will be coming soonish.

**Comment by mlubin** [comment]
Ok, thanks!
