### ISSUE TITLE
Failed to Initialize Julia

### ISSUE THREAD

**Issue by lqdc** [JuliaLang/pyjulia#42]
I am getting the following exception when doing the tests or attempting to initialize julia with `julia.Julia()`

Steps performed to install on Ubuntu 14.04:

install julia version 0.3.11 via the ppa for release stable.
set up environment in PyCall with `ENV["PYTHON"] = "/usr/bin/python3"`
used `Pkg.build("PyCall")`

    INFO: Building PyCall
    INFO: PyCall is using /usr/bin/python3 (Python 3.4.3) at /usr/bin/python3, libpython = libpython3.4m
    using PyCall
    @pyimport math
    math.sin(math.pi / 4) - sin(pi / 4)  # returns 0.0

So PyCall works.

now with Python:

     $/usr/bin/python3
     >>>import julia
     >>>julia.Julia()

    Warning: error initializing module PyCall:
    PyCall.PyError(msg=":PyImport_ImportModule", T=PyCall.PyObject(o=0x0000000005da8240), val=PyCall.PyObject(o=0x0000000004d552b0), traceback=PyCall.PyObject(o=0x0000000004d574c8))
    Traceback (most recent call last):
      File "/home/user/libs/pyjulia/julia/core.py", line 289, in __init__
        self.call('pyinitialize(C_NULL)')
      File "/home/user/libs/pyjulia/julia/core.py", line 329, in call
        .format(exception_type, exception_msg, src))
    julia.core.JuliaError: Exception 'UndefVarError' ocurred while calling julia code:
    <couldn't get stack>

    Code:
    pyinitialize(C_NULL)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/user/libs/pyjulia/julia/core.py", line 291, in __init__
        raise JuliaError("Failed to initialize PyCall package")
    julia.core.JuliaError: Failed to initialize PyCall package

I tried the same thing with Python2 with the same results.

**Comment by fc4321** [comment]
I had a similar issue on Mac OS and the problem was apparently remedied after commenting out lines 288-291 in julia/core.py

it seems that pyinitialize is no longer an export of PyCall

**Comment by lqdc** [comment]
The method worked for 0.3, but for 0.4 I'm getting a new error:
```
ERROR: UndefVarError: dlpath not defined
 in process_options at ./client.jl:284
 in _start at ./client.jl:411
---------------------------------------------------------------------------
JuliaError                                Traceback (most recent call last)
<ipython-input-2-4009d3e1be3e> in <module>()
----> 1 julia.Julia()

/home/roman/libs/pyjulia/julia/core.py in __init__(self, init_julia, jl_init_path)
    242                 sysimg_relpath_alt = os.path.join(os.path.relpath(libjulia_dir, JULIA_HOME), 'julia',"sys.ji")
    243             except:
--> 244                 raise JuliaError('error starting up the Julia process')
    245 
    246             if not os.path.exists(libjulia_path):

JuliaError: error starting up the Julia process
```
